dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "14"
jobs:
  fast_finish: true
install:
  - npm install
script:
  - npm run build
  - npm run test:prod
after_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/clover.xml
