dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "14"
jobs:
  fast_finish: true
install:
  - npm install
script:
  - npm run build
  - npm run test
